#' Box plot for One vs More Variables: immunity Results
#'
#' @param col1 column names of input data frame, only one
#' @param col2 column names of input data frame, One or More
#' @param mat Expression Matrix or data frame, not tibble
#' @param group group column name or null, default NULL
#' @return A ggplot2 object of box plot
#' @author Yangming si
#' @examples
#' # example 1: Low High group
#' df1 <- data.frame(gene1 = rnorm(50), gene2 = rnorm(50))
#' df2 <- data.frame(gene3 = rnorm(50), gene4 = rnorm(50))
#' df <- cbind(df1, df2)
#' ggboxplot2("gene1", "gene3", df)
#' # example 2: multi group
#' df1 <- data.frame(gene1 = rnorm(30), gene2 = rnorm(30), gene3 = rnorm(30))
#' df2 <- data.frame(group = rep(c(1, 2, 3), each = 10))
#' df <- cbind(df1, df2)
#' ggboxplot2("gene1", "group", df, group = "group")
#' @export

ggboxplot2 <- function(col1, col2, mat, group = NULL) {
  gene <- as.numeric(mat[, col1])
  if (is.null(group)) {
    group <- if_else(gene > median(gene),
                     paste0(col1, "-High"),
                     paste0(col1, "-Low")
    )
    group <- factor(group, levels = c(
      paste0(col1, "-Low"),
      paste0(col1, "-High")
    ))
    if (length(col2) > 1) {
      box <- reshape2::melt(data.frame(
        group = group,
        mat[, col2]
      ))
    } else {
      box <- reshape2::melt(data.frame(
        group = group,
        mat[, col2]
      ))
      box$variable <- col2
    }

    box$variable <- str_replace_all(box$variable, "\\.", " ")

    p <- ggpubr::ggboxplot(box,
                           x = "variable", y = "value", color = "group",
                           palette = c("#00AFBB", "#E7B800")
    ) +
      # easy_rotate_x_labels(angle = 45, teach = TRUE)
      # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
      ggpubr::stat_compare_means(aes(group = group), label = "p.signif") +
      xlab("") + ylab("")
  } else {
    box <- mat[, c(col1, group)]
    my_comparisons <- Group2Comparison(unique(sort(as.character(box[, group]))))
    p <- ggpubr::ggboxplot(box, x = group,
                           y = col1, color = group) +
      ggpubr::stat_compare_means(ggplot2::aes(group = group),
                                 comparisons = my_comparisons,
                                 label = "p.signif") +
      ggplot2::xlab(group) + ggplot2::ylab(col1)
  }


  return(p)
}

#' Covert Group vector to a comparison list
#'
#' @param group group character vector
#' @return A group comparison list
#' @author Yangming si
#' @examples
#' group <- as.character(1:3)
#' Group2Comparison(group)
#' @export

Group2Comparison <- function(group){
  return(combn(group, 2, simplify = FALSE))
}

#' Scatter plot for Two Variables
#'
#' @param col1 column names of input data frame
#' @param col2 Ccolumn names of input data frame
#' @param mat Expression Matrix or data frame, not tibble
#' @param trend pos or neg
#' @param method one of "pearson", "kendall", or "spearman"
#' @return A ggplot2 object of scatter plot
#' @author Yangming si
#' @examples
#' df1 <- data.frame(gene1 = rnorm(50), gene2 = rnorm(50))
#' df2 <- data.frame(gene3 = rnorm(50), gene4 = rnorm(50))
#' df <- cbind(df1, df2)
#' ggscatter2("gene1", "gene3", df)
#' @export

ggscatter2 <- function(col1, col2, mat, trend = "pos", method = "pearson") {
  scatter <- data.frame(x = mat[, col1], y = mat[, col2])

  trend <- ifelse(cor.test(scatter$x, scatter$y,
    method = method
  )$estimate > 0,
  "pos", "neg"
  )
  if (trend == "pos") {
    label.x <- mean(scatter$x)
    label.y <- max(scatter$y) - mean(scatter$y) / 2
  }
  if (trend == "neg") {
    label.x <- mean(scatter$x)
    label.y <- max(scatter$y) - mean(scatter$y) / 2
  }
  p <- ggpubr::ggscatter(scatter,
    x = "x", y = "y",
    fill = "black",
    color = "black", shape = 21, size = 1, # Points color, shape and size
    # add = "reg.line", # Add regressin line
    xlab = col1, ylab = col2,
    add.params = list(color = "blue", fill = "lightgray"), # Customize reg.line
    conf.int = TRUE, # Add confidence interval
    cor.coef = TRUE, # Add correlation coefficient. see ?stat_cor
    cor.coeff.args = list(
      method = method,
      label.x = label.x,
      label.y = label.y,
      label.sep = "\n"
    )
  ) +
    ggplot2::geom_smooth(method = "lm")
  return(p)
}

#' Plots wordcloud.
#'
#' @description Plots word cloud of mutated genes or altered cytobands with size proportional to the event frequency.https://gist.github.com/PoisonAlien/3f8752a89c1d63f64afe55b441621223
#' @param input an \code{\link{MAF}} or \code{\link{GISTIC}} object generated by \code{\link{read.maf}} or \code{\link{readGistic}}
#' @param minMut Minimum number of samples in which a gene is required to be mutated.
#' @param col vector of colors to choose from.
#' @param top Just plot these top n number of mutated genes.
#' @param genesToIgnore Ignore these genes.
#' @param ... Other options passed to \code{\link{wordcloud}}
#' @return nothing.
#' @examples
#' library(maftools)
#' laml.input <- system.file("extdata", "tcga_laml.maf.gz", package = "maftools")
#' laml <- read.maf(maf = laml.input, useAll = FALSE)
#' geneCloud(input = laml, minMut = 5, top = 5)
#' @importFrom wordcloud wordcloud
#' @export


geneCloud <- function(input, minMut = 3, col = NULL, top = NULL, genesToIgnore = NULL, ...) {
  if (class(input)[1] == "GISTIC") {
    gs <- getCytobandSummary(input)

    col <- ifelse(test = gs$Variant_Classification %in% "Amp", yes = "red", no = "blue")
    wordcloud::wordcloud(
      words = gs[, Cytoband], freq = -log10(gs[, qvalues]),
      colors = col, ordered.colors = TRUE, rot.per = 0.2, ...
    )
  } else {
    gs <- getGeneSummary(x = input)

    # Either choose top n genes or > minMut
    if (!is.null(top)) {
      gs <- gs[1:top]
    } else {
      gs <- gs[gs$MutatedSamples >= minMut,]
    }

    # If any genes to ignore
    if (!is.null(genesToIgnore)) {
      gs <- gs[!Hugo_Symbol %in% genesToIgnore]
    }

    if (is.null(col)) {
      col <- c(RColorBrewer::brewer.pal(12, name = "Paired"), RColorBrewer::brewer.pal(9, name = "Set1"), "black")
    }

    wordcloud::wordcloud(
      words = gs[["Hugo_Symbol"]], freq = gs[["MutatedSamples"]],
      colors = col, random.color = TRUE, rot.per = 0.2, ...
    )
  }
}
